name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint discord discord-py-slash-command gitpython pydictionary translate wikipedia wolframalpha google requests pygount
    - name: Analysing the code with pylint
      run: |
        find . | grep .py$ | grep --invert-match scraps | xargs python3 -m pylint --fail-under=9.5
